language: python
python:
  - "3.8"
install: "pip install -r requirements.txt"
# before_script:
#   - cp .env.example .env
   - python manage.py migrate
script:
  - flake8 cmdbox
  - coverage run manage.py test --settings=cmdbox.tests_settings
after_success:
  - coveralls
